[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'



[[plugins]]
repo = 'Shougo/neosnippet'

on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

hook_add = '''
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
    
'''

hook_source = '''
    let g:neosnippet#snippets_directory = dein#get('neosnippet-snippets').path.'/neosnippets'
'''



[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_smart_case = 1
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>

    function! s:my_cr_function()
      return pumvisible() ? deoplete#mappings#close_popup() : "\<CR>"
    endfunction
'''
on_i = 1

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1








