[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['unite.vim']
on_path = '.*'

hook_add = '''
    let g:neomru#file_mru_limit = 10000
'''

#depends = ['denite.nvim']
[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = ['unite.vim']
on_path = '.*'

#depends = ['denite.nvim']

hook_add = '''
    let g:neoyank#limit = 10000
'''

#[[plugins]]
#repo = 'Shougo/denite.nvim'
#on_event = 'BufRead'
#hook_add = '''
#    nmap <silent> ,uf :<C-u>Denite unite:file_rec<CR>
#    nmap <silent> ,ul :<C-u>Denite line<CR>
#    nmap <silent> ,ug :<C-u>Denite grep<CR>
#    nmap <silent> ,uu :<C-u>Denite unite:file_mru<CR>
#    nmap <silent> ,uy :<C-u>Denite neoyank<CR>
#    nmap <silent> ,ud :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>
#    nmap <silent> <buffer> <expr> <C-j> unite#do_action('split')
#'''
#
#
#hook_post_source = '''
#    call denite#custom#var('file_rec', 'command',
#    \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
#    call deinte#custom#var('grep', 'command',
#    \ ['ag', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
#'''
#

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/unite.vim'
on_event = 'BufRead'
hook_add = '''
    let g:unite_enable_start_insert = 1
    nmap let g:unite_enable_smart_case = 1
    let g:unite_enable_ignore_case = 1
    let g:unite_source_file_mru_filename_format = ''
    nmap <silent> ,uf :<C-u>UniteWithBufferDir -buffer-name=file file<CR>
    nmap <silent> ,ur :<C-u>Unite -buffer-name=register register<CRdotfiles/dotlink.sh>
    nmap <silent> ,ud :<C-u>Unite file<CR>
    nmap <silent> ,um :<C-u>Unite file_mru<CR>
    nmap <silent> ,uy :<C-u>Unite history/yank<CR>
    nmap <silent> ,uu :<C-u>Unite buffer file_mru<CR>
    nmap <silent> ,g  :<C-u>Unite grep: -buffer-name=search-buffer<CR>
    nmap <silent> ,cg :<C-u>Unite grep: -buffer-name=search-buffer<CR><C-R><C-W>
    nmap <silent> ,r  :<C-u>UniteResume search-buffer<CR>
    au FileType unite nmap <silent> <buffer> <expr> <C-j> unite#do_action('split')
    au FileType unite imap <silent> <buffer> <expr> <C-j> unite#do_action('split')
    au FileType unite nmap <silent> <buffer> <expr> <C-k> unite#do_action('vsplit')
    au FileType unite imap <silent> <buffer> <expr> <C-k> unite#do_action('vsplit')
    if executable('ag')
        let g:unite_source_grep_command = 'ag'
        let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
        let g:unite_source_grep_recursice_opt = ''
    endif
'''


[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''

